### ISSUE TITLE
Zero or negative time interval not supported

### ISSUE THREAD

**Issue by slimm609** [elastic/packetbeat-dashboards#2]
using the dashboards 1.0.0-beta with kibana 4.0.2 and elasticsearch 1.5.2  I get these errors several times whenever any dashboard is accessed. 

[2015-06-08 10:39:44,766][DEBUG][action.search.type       ] [Phil Urich] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [packetbeat-2015.06.08][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"aggs":{"2":{"date_histogram":{"field":"timestamp","interval":"0ms","pre_zone":"-04:00","pre_zone_adjust_large_interval":true,"min_doc_count":1,"extended_bounds":{"min":1433774084563,"max":1433774384563}},"aggs":{"3":{"histogram":{"field":"responsetime","interval":10},"aggs":{"1":{"sum":{"field":"count"}}}}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"_":{}}},"query":{"filtered":{"query":{"match_all":{}},"filter":{"bool":{"must":[{"query":{"query_string":{"analyze_wildcard":true,"query":"_"}}},{"range":{"@timestamp":{"gte":1433774084566,"lte":1433774384566}}}],"must_not":[]}}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: Zero or negative time interval not supported
        at org.elasticsearch.common.rounding.TimeZoneRounding$Builder.<init>(TimeZoneRounding.java:68)
        at org.elasticsearch.common.rounding.TimeZoneRounding.builder(TimeZoneRounding.java:42)
        at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramParser.parse(DateHistogramParser.java:205)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:130)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:77)
        at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more

[2015-06-08 10:39:44,762][DEBUG][action.search.type       ] [Phil Urich] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [packetbeat-2015.06.08][0]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(ConstantScore(_:_)) +cache(@timestamp:[1433774084566 TO 1433774384566])))],from[-1],size[0]: Parse Failure [Failed to parse source [{"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"_":{}}},"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"_"}},"filter":{"bool":{"must":[{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}}},{"range":{"@timestamp":{"gte":1433774084566,"lte":1433774384566}}}],"must_not":[]}}}},"size":0,"aggs":{"2":{"date_histogram":{"field":"timestamp","interval":"0ms","pre_zone":"-04:00","pre_zone_adjust_large_interval":true,"min_doc_count":1,"extended_bounds":{"min":1433774084560,"max":1433774384561}},"aggs":{"1":{"percentiles":{"field":"responsetime","percents":[75,95,99]}}}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: Zero or negative time interval not supported
        at org.elasticsearch.common.rounding.TimeZoneRounding$Builder.<init>(TimeZoneRounding.java:68)
        at org.elasticsearch.common.rounding.TimeZoneRounding.builder(TimeZoneRounding.java:42)
        at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramParser.parse(DateHistogramParser.java:205)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:130)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:77)
        at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more

[2015-06-08 10:39:44,764][DEBUG][action.search.type       ] [Phil Urich] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [packetbeat-2015.06.08][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"aggs":{"2":{"date_histogram":{"field":"timestamp","interval":"0ms","pre_zone":"-04:00","pre_zone_adjust_large_interval":true,"min_doc_count":1,"extended_bounds":{"min":1433774084563,"max":1433774384563}},"aggs":{"3":{"terms":{"field":"type","size":5,"order":{"1":"desc"}},"aggs":{"1":{"sum":{"field":"count"}}}}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"_":{}}},"query":{"filtered":{"query":{"query_string":{"query":"type: mysql or type: pgsql","analyze_wildcard":true}},"filter":{"bool":{"must":[{"query":{"query_string":{"analyze_wildcard":true,"query":"_"}}},{"range":{"@timestamp":{"gte":1433774084566,"lte":1433774384566}}}],"must_not":[]}}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: Zero or negative time interval not supported
        at org.elasticsearch.common.rounding.TimeZoneRounding$Builder.<init>(TimeZoneRounding.java:68)
        at org.elasticsearch.common.rounding.TimeZoneRounding.builder(TimeZoneRounding.java:42)
        at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramParser.parse(DateHistogramParser.java:205)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:130)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:77)
        at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more

**Comment by bascht** [comment]
Same here.
Packetbeat 1.0.0-beta3, ES 1.7.11, Kibana 4.1.1.

**Comment by bascht** [comment]
@slimm609 Try selecting a proper interval for the saved searches:
![screenshot-2015-09-10-194424-360x430](https://cloud.githubusercontent.com/assets/51264/9796072/75db5f3a-57f4-11e5-870c-c51c736de944.png)

Fixed it for me. :)

**Comment by monicasarbu** [comment]
Closing this issue as it is likely a configuration error.

**Comment by damm** [comment]
Question is what was the configuration error?

**Comment by bascht** [comment]
@damm The prebuilt-dashboards didn't have a interval selected (see my screenshot).

**Comment by damm** [comment]
@bascht yeah it has to do with the default search I think? I ended up forking this repo as I was only evaluating topbeats 

Removed all the things that broke Kibana for me; running `./load.sh -url http://es:9200` breaks Kibana.

https://github.com/elastic/beats-dashboards/blob/master/dashboards/search/Default-Search.json

That default search is what personally broke Kibana, defaults to packetbeat index.  However my default pattern is to logstash-

The end result was that error listed.  In the discover panel you cannot use the time picker; it's only available in Dashboard option.  It basically has no time interval set so it actually is looking back _DAYS_

Deleting the logstash- pattern and re-making it makes Kibana useful again.

**Comment by damm** [comment]
I opened #49 as I recently ran into this after running load.sh from here.  It's not a configuration error; it's because the default search? is looking at the wrong indice for the default search.  My default pattern is logstash- and it's looking in `packeatbeat-*` to draw the histogram.

**Comment by bascht** [comment]
Sorry, busy week. I didn't have time to look into this, are you still stuck and is there anything I can help out with?
